### ISSUE TITLE
Live instance is not working

### ISSUE THREAD

**Issue by schadokar** [gsuitedevs/drive-quickeditors#10]
Error: Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

**Comment by andreasplesch** [comment]
same here.

**Comment by sqrrrl** [comment]
Temporarily removed the link, but will look in to restoring it and having the app verified.

**Comment by schadokar** [comment]
okay, thanks for the update. Then I am closing it for now.
