### ISSUE TITLE
Live Instance link in README.md broken

### ISSUE THREAD

**Issue by czechtech** [gsuitedevs/drive-quickeditors#7]
The link to "live instance" navigates to a 404.

Broken:
http://googledrive.github.io/web-quickeditor

**Comment by erickoledadevrel** [comment]
Thanks for reporting this! The correct URL appears to be:

http://gsuitedevs.github.io/drive-quickeditors

However the app isn't loading at that URL, likely because the client ID being used isn't whitelisted for this new URL. @sqrrrl - do you have access to the Cloud project being used?

**Comment by sqrrrl** [comment]
Yep, updated the project to the new URL. Still unverified, but works now. Note, *must* be over https -- https://gsuitedevs.github.io/drive-quickeditors/

Will send a PR to fix the readme.
