### ISSUE TITLE
Still loading only

### ISSUE THREAD

**Issue by shnathoskhan** [gsuitedevs/drive-quickeditors#9]
No signin screen appear. still loading

![image](https://user-images.githubusercontent.com/32763360/60951688-4b098080-a317-11e9-8e16-ef8547d4e112.png)

**Comment by sqrrrl** [comment]
Need more info -- Any error messages on the console? Failed network requests?

**Comment by vub** [comment]
Same issue.

There are no errors in console.
No network error.

But the screen still loading...
